dubbo:
  application:
    name:  dubbo-consumer
  registry:
    address: zookeeper://49.234.97.199:2181
    client: curator
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
    serialization: kryo
  scan:
    basePackages: com.walter.dubbotest.service

server:
  port: 8090